/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignments;

/**
 *
 * @author Dave
 */
public class Asgn_1_NumberAdditionUI extends javax.swing.JFrame {

  /**
   * Creates new form NumberAdditionUI
   */
  public Asgn_1_NumberAdditionUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    m_tfFirstNumber = new javax.swing.JTextField();
    m_tfSecondNumber = new javax.swing.JTextField();
    m_tfResult = new javax.swing.JTextField();
    m_btnAdd = new javax.swing.JButton();
    m_btnClear = new javax.swing.JButton();
    m_btnExit = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Assignment 1 - Number Adder");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Number Addition"));

    jLabel1.setText("First Number:");

    jLabel2.setText("Second Number: ");

    jLabel3.setText("Result: ");
    jLabel3.setToolTipText("");

    m_tfFirstNumber.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        m_tfFirstNumberActionPerformed(evt);
      }
    });

    m_btnAdd.setText("Add");
    m_btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        m_btnAddActionPerformed(evt);
      }
    });

    m_btnClear.setText("Clear");
    m_btnClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        m_btnClearActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel3))
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(m_tfFirstNumber)
              .addComponent(m_tfSecondNumber)
              .addComponent(m_tfResult))
            .addContainerGap())
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(0, 151, Short.MAX_VALUE)
            .addComponent(m_btnAdd)
            .addGap(18, 18, 18)
            .addComponent(m_btnClear)
            .addGap(42, 42, 42))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(m_tfFirstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(m_tfSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(m_tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(m_btnAdd)
          .addComponent(m_btnClear))
        .addContainerGap(21, Short.MAX_VALUE))
    );

    m_tfFirstNumber.getAccessibleContext().setAccessibleName("");

    m_btnExit.setText("Exit");
    m_btnExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        m_btnExitActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(m_btnExit)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(28, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(m_btnExit)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void m_tfFirstNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tfFirstNumberActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_m_tfFirstNumberActionPerformed

  private void m_btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnExitActionPerformed
    //System.exit(0);
    this.dispose();
  }//GEN-LAST:event_m_btnExitActionPerformed

  private void m_btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnClearActionPerformed
    m_tfFirstNumber.setText("");
    m_tfSecondNumber.setText("");
    m_tfResult.setText("");
  }//GEN-LAST:event_m_btnClearActionPerformed

  private void m_btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnAddActionPerformed
    float num1, num2, result;
    num1 = Float.parseFloat(m_tfFirstNumber.getText());
    num2 = Float.parseFloat(m_tfSecondNumber.getText());
    result = num1 + num2;
    m_tfResult.setText(String.valueOf(result));
  }//GEN-LAST:event_m_btnAddActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Asgn_1_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Asgn_1_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Asgn_1_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Asgn_1_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Asgn_1_NumberAdditionUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton m_btnAdd;
  private javax.swing.JButton m_btnClear;
  private javax.swing.JButton m_btnExit;
  private javax.swing.JTextField m_tfFirstNumber;
  private javax.swing.JTextField m_tfResult;
  private javax.swing.JTextField m_tfSecondNumber;
  // End of variables declaration//GEN-END:variables
}
